baseURL = "https://gurko45.org/"
title = "Галерия „Лира“"
languageCode = "bg"

[menu]

  [[menu.main]]
    identifier = "exhibitions"
    name = "Изложби"
    url = "/exhibitions"
    weight = 1

  [[menu.main]]
    identifier = "gallery"
    name = "Галерия"
    url = "/gallery"
    weight = 2

  [[menu.main]]
    identifier = "archive"
    name = "Сграда"
    url = "/archive"
    weight = 3

  [[menu.main]]
    identifier = "contacts"
    name = "Контакти"
    url = "/contacts"
    weight = 4


disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Ticker  Items

[[params.tickerItems]]
text = "Антонен Буши / Image-Diverted Situations / 03.-04.25 / ул. „Ген. Й. Гурко“ 45"
[[params.tickerItems]]
text = "Антонен Буши / Image-Diverted Situations / 03.-04.25 / ул. „Ген. Й. Гурко“ 45"
[[params.tickerItems]]
text = "Антонен Буши / Image-Diverted Situations / 03.-04.25 / ул. „Ген. Й. Гурко“ 45"
[[params.tickerItems]]
text = "Антонен Буши / Image-Diverted Situations / 03.-04.25 / ул. „Ген. Й. Гурко“ 45"
[[params.tickerItems]]
text = "Антонен Буши / Image-Diverted Situations / 03.-04.25 / ул. „Ген. Й. Гурко“ 45"
[params]
footerText = "Проектът се осъществява с подкрепата на Национален фонд „Култура“, програма „Дебюти“."
