baseURL = "http://example.com/"
title = "Моят сайт"
languageCode = "bg-bg"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Начало"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "exhibitions"
    name = "Изложби"
    url = "/exhibitions"
    weight = 2
